### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by keintek** [sndcode/WoW-PServer-Launcher#1]
Hi, I want to try your launcher, but I can't find the www folder, can you help me?

**Comment by darkmoi31** [comment]
me to i have this trouble ....

**Comment by darkmoi31** [comment]
i have found ;)
https://github.com/yitugege/WoW-PServer-Launcher/tree/master/www/wow

**Comment by sndcode** [comment]
@darkmoi31  @keintek 
it is another repo here : https://github.com/sndcode/WoW-Pserver-Launcher-Backend-Scripts
