### ISSUE TITLE
Server 500 error

### ISSUE THREAD

**Issue by ctmwow** [sndcode/WoW-PServer-Launcher#1]
I used PHP 5.5
Could you tell me how to set it up in detail? I tried again and again all afternoon and failed.

**Comment by ctmwow** [comment]
Oh, I used Dreamweaver to modify the default PHP file and got it done.
But there will be unresponsive problems. Can we repair them better?

**Comment by ctmwow** [comment]
If url_base has a port, can't it connect to the server?

**Comment by ctmwow** [comment]
AZ335 Test Display Online

434 Displays OFFline

Can you tell me how to change it?

**Comment by sndcode** [comment]
Well where exactly are you stuck ? and which code is throwing a break ?
